# Generated by Django 5.2.6 on 2025-09-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_rubric_subrubric_superrubric_rubric_super_rubric"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rubric",
            name="name",
            field=models.CharField(max_length=30, unique=True, verbose_name="Название"),
        ),
    ]
